image: oven-sh/bun:latest

before_script:
  - bun install --frozen-lockfile

pages:
  stage: deploy
  script:
    - bun run build 
    - mv .next public
  artifacts:
    paths:
      - public 
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH