include:
  - project: pipelines/pipelines
    ref: master
    file:
      - "/jobs/build.yaml"
      - "/jobs/docker.yaml"
      - "/jobs/rules.yaml"

.global-variables:
  variables:
    SSH_USER: "$ENV_SSH_USER"
    SSH_HOST: "$ENV_SSH_HOST"
    SSH_PRIVATE_KEY_BASE64: "$ENV_PRIVATE_KEY_BASE64"
    SSL_CERTIFICATE: "$SSL_CERTIFICATE"
    SSL_PRIVATE_KEY: "$SSL_PRIVATE_KEY"

stages:
  - build
  - deploy

build:
  stage: build
  extends:
    - .build
    - .rules-merge-or-master

deploy:
  stage: deploy
  extends:
    - .docker_run
    - .global-variables
    - .rules-merge-or-master
  variables:
    OPT_DOCKER: "-p 443:443"
  script:
    - apk add --no-cache openssl
    - |
      mkdir -p /etc/nginx/ssl
    - |

      echo "$SSL_CERTIFICATE" | base64 -d > /etc/nginx/ssl/fullchain.pem
      echo "$SSL_PRIVATE_KEY" | base64 -d > /etc/nginx/ssl/privkey.pem
    - |
      if [ ! -f "/etc/nginx/ssl/fullchain.pem" ] || [ ! -f "/etc/nginx/ssl/privkey.pem" ]; then
        echo "Ошибка: SSL-сертификат или приватный ключ не найдены!"
        exit 1
      fi
    - docker-compose down || true
    - docker-compose up -d --build
