image: oven-sh/setup-bun@v2

before_script:
  - bun install --production

pages:
  stage: deploy
  script:
    - bun run build
    - mv .next public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
